# Generated by Django 3.0.3 on 2020-04-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_agg_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['date']},
        ),
    ]
