# Generated by Django 3.0.3 on 2020-04-17 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_agg_api', '0002_auto_20200414_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['date_time']},
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='date',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='time',
        ),
        migrations.AddField(
            model_name='temperature',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
